//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.App.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRole
    {
        public int IdMemberRole { get; set; }
        public int IdMembership { get; set; }
        public int IdRole { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual Role Role { get; set; }
    }
}
